### ISSUE TITLE
Cannot upload in Linux

### ISSUE THREAD

**Issue by lthiery** [Xmegaduino/Xmegaduino#31]
Regardless of whether trying to do it over USB or with a programmer, the classic Java error occurs:

```
java.lang.NullPointerException
    at java.util.HashMap.putAll(HashMap.java:515)
    at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:210)
    at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:60)
    at processing.app.Sketch.upload(Sketch.java:1719)
    at processing.app.Sketch.exportApplet(Sketch.java:1625)
    at processing.app.Sketch.exportApplet(Sketch.java:1597)
    at processing.app.Editor$DefaultExportAppHandler.run(Editor.java:2439)
    at java.lang.Thread.run(Thread.java:701)
```

A little stumped at the moment but I will post back if I find a solution.

**Comment by lthiery** [comment]
Is is also worth mentioning that I am running the arduino application with sudo just to avoid any permissions issues.

Also, the following warnings appear during launch:

```
Could not find boards.txt in /home/louis/arduino-1.5.6-xmegaduino-beta5/hardware/arduino/bootloaders/boards.txt. Is it pre-1.5?
Could not find boards.txt in /home/louis/arduino-1.5.6-xmegaduino-beta5/hardware/arduino/firmwares/boards.txt. Is it pre-1.5?
Board arduino:xmega:api doesn't define a 'build.board' preference. Auto-set to: XMEGA_API
Board arduino:xmega:sfe doesn't define a 'build.board' preference. Auto-set to: XMEGA_SFE
Board arduino:xmega:xplain doesn't define a 'build.board' preference. Auto-set to: XMEGA_XPLAIN
Board arduino:xmega:akafuino doesn't define a 'build.board' preference. Auto-set to: XMEGA_AKAFUINO
Board arduino:xmega:xmega doesn't define a 'build.board' preference. Auto-set to: XMEGA_XMEGA

```

**Comment by karlbackstrom** [comment]
Hi Louis and thank you for the bug report. Will check and see what can be done for these issues.

**Comment by lthiery** [comment]
I tried open-jdk7 and I also tried to build it from source; both to no avail

Still trying to figure out ways to narrow it down but I have yet to dig into the java part of this project

**Comment by karlbackstrom** [comment]
I don't have any news on my side either, but will try this out during the week.

Could it be that you have another jdk installed as well?

**Comment by lthiery** [comment]
I uninstalled jdk-6 and installed jdk-7 when I tested it so I'm fairly certain I was using jdk-7.

I also realized that I haven't used arduino 1.5 at all - not even the main release - so I've tested that one as well - it has the same bug. So I'll see if I can get some help from there...

**Comment by karlbackstrom** [comment]
Did you find out what was wrong with both the official Arduino and Xmegaduino?
